### ISSUE TITLE
Support for folders?

### ISSUE THREAD

**Issue by Snussune** [CrazyOldWizard/TV-Show-Sorter#5]
I would like to see support for folders instead of only filenames.
Maybe the config file could contain a setting to use folder or files?

Example:

Breaking.Bad.S01E01.HDTV.x264-somegroup
Breaking.Bad.S01E02.HDTV.x264-somegroup
Breaking.Bad.S01E03.HDTV.x264-somegroup

^ Those are folders and would be sorted in the same way as the files are being sorted now.

Breaking Bad/Season 01/Breaking.Bad.S01E01.HDTV.x264-somegroup
Breaking Bad/Season 01/Breaking.Bad.S01E02.HDTV.x264-somegroup
Breaking Bad/Season 01/Breaking.Bad.S01E03.HDTV.x264-somegroup

**Comment by CrazyOldWizard** [comment]
I have a WIP version of this that I haven't run yet.  I will mess around with it more when I get home.  For now, the build in this branch should in theory have the ability to sort by folders. But like I said, I haven't tested this build yet.

https://github.com/CrazyOldWizard/TV-Show-Sorter/tree/sort-by-folders/TV%20Show%20Sorter/bin/Release
